async (page) => {
  const snapshot = () => page.evaluate(() => window.__castleBattle.snapshot())
  const check = (condition, message) => { if (!condition) throw new Error(message) }
  const results = {}
  await page.goto('http://127.0.0.1:5175/works/castle-battle')
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('button', { name: '踏入钟庭' }).click()
  await page.keyboard.down('Space')
  await page.waitForFunction(() => window.__castleBattle.snapshot().phase === 'victory', null, { timeout: 25000 })
  await page.keyboard.up('Space')
  results.victory = await snapshot()
  check(results.victory.phase === 'victory' && results.victory.kills === 8, 'Real combat must defeat every guard')
  await page.getByRole('heading', { name: '通关成功' }).waitFor()
  await page.screenshot({ path: 'output/playwright/castle-victory-desktop.png' })
  await page.getByRole('button', { name: '再次挑战' }).click()
  results.reset = await snapshot()
  check(results.reset.kills === 0 && results.reset.player.health === 100 && results.reset.enemies.every(unit => unit.health > 0), 'Retry must reset every combatant')
  await page.getByRole('button', { name: '暂停', exact: true }).click()
  const paused = await snapshot()
  await page.waitForTimeout(600)
  check((await snapshot()).elapsed === paused.elapsed, 'Pause must freeze simulation')
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.keyboard.press('r')
  check((await snapshot()).phase === 'paused', 'Settings must block restart hotkey')
  await page.getByRole('button', { name: '精细', exact: true }).click()
  check(await page.getByRole('button', { name: '精细', exact: true }).getAttribute('aria-pressed') === 'true', 'Quality must change')
  await page.getByRole('switch', { name: '音效' }).click()
  check(await page.getByRole('switch', { name: '音效' }).getAttribute('aria-checked') === 'false', 'Mute must change')
  await page.getByRole('button', { name: '均衡', exact: true }).click()
  await page.getByRole('button', { name: '关闭设置', exact: true }).click()
  check((await snapshot()).phase === 'paused', 'Settings must retain previous paused state')
  await page.getByRole('button', { name: '继续征途' }).click()
  const origin = (await snapshot()).player.position
  await page.keyboard.down('d')
  await page.waitForTimeout(500)
  await page.keyboard.up('d')
  results.moved = await snapshot()
  check(Math.abs(results.moved.player.position[0] - origin[0]) > 0.5, 'Movement must change world position')
  await page.getByRole('button', { name: '闪避', exact: true }).click()
  check((await snapshot()).player.stamina < 90, 'Dodge must consume stamina')
  await page.getByRole('button', { name: '锁定目标', exact: true }).click()
  check(await page.getByRole('button', { name: '锁定目标', exact: true }).getAttribute('aria-pressed') === 'true', 'Lock must acquire target')
  await page.getByRole('button', { name: '锁定目标', exact: true }).click()
  const yaw = (await snapshot()).yaw
  await page.mouse.move(780, 440)
  await page.mouse.down({ button: 'right' })
  await page.mouse.move(920, 470, { steps: 5 })
  await page.mouse.up({ button: 'right' })
  check(Math.abs((await snapshot()).yaw - yaw) > 0.2, 'Right drag must rotate camera')
  await page.waitForFunction(() => window.__castleBattle.snapshot().player.health <= 70, null, { timeout: 22000 })
  const injured = await snapshot()
  await page.getByRole('button', { name: '饮用药剂', exact: true }).click()
  results.healed = await snapshot()
  check(results.healed.player.potions === 2 && results.healed.player.health > injured.player.health, 'Potion must heal and be consumed')
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.keyboard.press('r')
  check((await snapshot()).phase === 'paused', 'Settings opened during play must remain paused')
  await page.keyboard.press('p')
  check((await snapshot()).phase === 'playing', 'Closing settings must restore prior play state')
  await page.waitForFunction(() => window.__castleBattle.snapshot().phase === 'dead', null, { timeout: 35000 })
  await page.getByRole('heading', { name: '你已倒下' }).waitFor()
  await page.screenshot({ path: 'output/playwright/castle-death-desktop.png' })
  results.dead = await snapshot()
  return results
}
