<script setup>
import { onMounted, onUnmounted } from 'vue'
import ContactSection from './ContactSection.vue'
defineProps({ onOpen: Function, onOpenCastle: Function })
const dots=Array.from({length:24},(_,i)=>({x:(i*37)%88+5,y:(i*53)%78+8}))
let observer
onMounted(()=>{ observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('show');observer.unobserve(entry.target)}}),{threshold:.12}); document.querySelectorAll('.reveal').forEach(el=>observer.observe(el)) })
onUnmounted(()=>observer?.disconnect())
</script>
<template><div class="site"><header class="top wrap"><a class="logo" href="#top">LUXI<b>XI</b><i>✳</i></a><nav><a href="#about">ABOUT</a><a href="#work">WORKS</a><a href="#contact">CONTACT</a></nav><span>● AVAILABLE FOR FUN</span></header><main><section class="hero wrap"><div class="hero-grid"/><div class="content"><div class="eyebrow">/ 个人档案 001 — 自由创作者</div><h1>露<span>西西</span></h1><p><strong>我把好奇心做成可玩的东西。</strong><br>动画、三维、交互和一点点不合时宜的想象。</p></div><div class="scroll">↓ 向下探索</div></section><section id="about" class="about wrap reveal"><div><div class="label">01 / A LITTLE ABOUT ME</div><h2>保持<br><em>好奇。</em></h2></div><div class="copy"><p>你好，我是露西西。一个喜欢把脑内画面变成立体世界的人。这里会慢慢放进我的实验、草稿、失败和突然灵光一现的作品。</p><p>之后每个项目都会从这里出发，去往它自己的小宇宙。</p><span class="stamp">STILL MAKING THINGS ✦</span></div></section><section id="work" class="work wrap reveal"><div class="work-head"><div><div class="label">02 / SELECTED WORKS</div><h2>作品集</h2></div></div><div class="cards"><a class="card data-card" href="/works/city-heatmap" @click.prevent="onOpen"><span class="tag">DATA VISUALIZATION / 2025</span><div class="cover-map"><i v-for="d in dots" :key="d.x+d.y" :style="{left:d.x+'%',top:d.y+'%'}"/></div><h3>全国城市<br>热力数据大屏 <span class="arrow">↗</span></h3></a><a class="card c2" href="/works/castle-battle" @click.prevent="onOpenCastle"><span class="tag">GAME / PLAY</span><h3>古堡战斗<br>小游戏</h3></a><a class="card c3" href="#"><span class="tag">3D / MODELING</span><h3>人体解剖<br>细节</h3></a><a class="card c4" href="#"><span class="tag">ARCHIVE / SPECULATIVE</span><h3>虚构物种<br>档案</h3></a><a class="card c5" href="#"><span class="tag">GAME / PLAY</span><h3>给大脑<br>找点麻烦</h3></a><a class="card c6" href="#"><span class="tag">COMING SOON</span><h3>更多<br>正在生成</h3></a></div></section><ContactSection /></main><footer class="wrap">© 2026 LUXIXI / MADE WITH CURIOSITY</footer></div></template>
