<script setup>
const stickers = [
  { name: '01 / 独眼奔跑怪', file: '/assets/stickers/01-one-eyed-runner.svg', note: '适合放在 Hero 角落，带一点笨拙的冲劲。' },
  { name: '02 / 自由涂鸦', file: '/assets/stickers/02-free-doodle.svg', note: '适合放在标题、滚动字幕或作品集入口旁。' },
  { name: '05 / 几何舞者', file: '/assets/stickers/05-paper-dancer.svg', note: '适合放在作品卡片之间，强化青春感。' },
]
</script>
<template><main class="sticker-preview-page"><header class="sticker-preview-head"><a href="/">LUXIXI<span>✳</span></a><p>STICKER LAB / 已选贴图</p><a class="back-link" href="/">返回首页 ↗</a></header><section class="sticker-preview-intro"><div><span class="eyebrow">03 SELECTED / INSTALLED ON HOME</span><h1>已经挑好<br><em>怪一点的。</em></h1></div><p>这三张透明 SVG 贴图已分别放入首页 Hero、作品集和保持联系板块。</p></section><section class="sticker-grid"><article v-for="sticker in stickers" :key="sticker.file" class="sticker-option"><div class="sticker-art"><img :src="sticker.file" :alt="sticker.name"></div><div class="sticker-meta"><h2>{{ sticker.name }}</h2><p>{{ sticker.note }}</p><a :href="sticker.file" target="_blank" rel="noopener">打开原图 ↗</a></div></article></section></main></template>
<style scoped>
.sticker-preview-page{min-height:100vh;background:#f4f0df;color:#111;padding:24px clamp(18px,5vw,80px) 70px;font-family:"Courier New","Microsoft YaHei",monospace}.sticker-preview-head{display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:18px;gap:20px}.sticker-preview-head>a:first-child{font:bold 24px Arial;color:#6057ff;text-decoration:none}.sticker-preview-head>a:first-child span{color:#ff694f}.sticker-preview-head p,.back-link{font-size:11px}.back-link{color:#111;text-underline-offset:5px}.sticker-preview-intro{display:grid;grid-template-columns:1.3fr .7fr;gap:12vw;align-items:end;padding:80px 0 46px}.eyebrow{color:#6057ff;font-size:11px}.sticker-preview-intro h1{font:900 clamp(52px,9vw,120px)/.82 Arial;margin:22px 0 0;letter-spacing:-.08em}.sticker-preview-intro h1 em{font-style:normal;color:#ff694f}.sticker-preview-intro>p{max-width:330px;line-height:1.9;border-left:3px solid #d8ff36;padding-left:18px}.sticker-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.sticker-option{border:2px solid #111;background:#fff;display:grid;grid-template-columns:1.1fr .9fr;min-height:300px;overflow:hidden;transition:transform .3s,box-shadow .3s}.sticker-option:hover{transform:translate(-5px,-6px) rotate(-1deg);box-shadow:9px 10px 0 #ff78b7}.sticker-option:nth-child(3){grid-column:1/-1}.sticker-art{min-height:300px;display:grid;place-items:center;background:#d8ff36;background-image:linear-gradient(#1111 1px,transparent 1px),linear-gradient(90deg,#1111 1px,transparent 1px);background-size:28px 28px}.sticker-option:nth-child(2) .sticker-art{background-color:#ff78b7}.sticker-option:nth-child(3) .sticker-art{background-color:#6057ff}.sticker-option:nth-child(4) .sticker-art{background-color:#fff}.sticker-option:nth-child(5) .sticker-art{background-color:#ff694f}.sticker-art img{width:min(78%,280px);height:240px;object-fit:contain;transition:transform .35s}.sticker-option:hover img{transform:scale(1.08) rotate(3deg)}.sticker-meta{padding:22px;display:flex;flex-direction:column;justify-content:flex-end}.sticker-meta h2{font:bold 25px/1.1 Arial;margin:0 0 12px}.sticker-meta p{font-size:12px;line-height:1.7;color:#4c4a40}.sticker-meta a{margin-top:20px;color:#6057ff;font-size:11px}@media(max-width:700px){.sticker-preview-head p{display:none}.sticker-preview-intro{display:block;padding:58px 0 34px}.sticker-preview-intro>p{margin-top:30px}.sticker-grid{grid-template-columns:1fr}.sticker-option,.sticker-option:nth-child(3){grid-column:auto;grid-template-columns:1fr}.sticker-art{min-height:260px}.sticker-meta{min-height:170px}}
</style>
